name: ci-flows

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - 'feat/*'
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code
        run: ruff check .

      - name: Format code
        run: ruff format .

      - name: Run tests
        run: |
            pytest *-tests.py --junitxml=junit/test-results.xml --cov=. --cov-report=xml
        working-directory: ${{ github.workspace }}

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both

      - name: Archive test and code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-results
          path: |
            **/test-results-*.xml
            coverage.xml
            code-coverage-results.md